#!/usr/bin/env python

# This file is for building as a Godot engine module.

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_2pt5d = env_modules.Clone()

env_2pt5d.add_source_files(env.modules_sources, "*.cpp")
env_2pt5d.add_source_files(env.modules_sources, "math/*.cpp")
env_2pt5d.add_source_files(env.modules_sources, "nodes/*.cpp")

if env.editor_build:
    SConscript("editor/SCsub")
